In [32]:
import numpy as np


In [33]:
random=np.random.random_sample((20,2))
print(random)

[[0.18428731 0.55482024]
 [0.7211177  0.70239494]
 [0.84762596 0.88522977]
 [0.72184946 0.40424016]
 [0.13175365 0.45782359]
 [0.04233896 0.18334159]
 [0.53809683 0.62668879]
 [0.95346348 0.15069883]
 [0.17723978 0.50313014]
 [0.20469355 0.36386604]
 [0.31155522 0.89941798]
 [0.96999736 0.52925504]
 [0.06510567 0.08527888]
 [0.94080292 0.58916964]
 [0.68906079 0.36215063]
 [0.07206619 0.09023895]
 [0.37070818 0.06541567]
 [0.32307269 0.54501816]
 [0.15927369 0.27373841]
 [0.49462728 0.17759489]]


In [34]:
time = np.arange(0,10,.5)
print(time)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [35]:
nrandom = np.insert(random, 0, time, axis=1)
print(nrandom)

[[0.         0.18428731 0.55482024]
 [0.5        0.7211177  0.70239494]
 [1.         0.84762596 0.88522977]
 [1.5        0.72184946 0.40424016]
 [2.         0.13175365 0.45782359]
 [2.5        0.04233896 0.18334159]
 [3.         0.53809683 0.62668879]
 [3.5        0.95346348 0.15069883]
 [4.         0.17723978 0.50313014]
 [4.5        0.20469355 0.36386604]
 [5.         0.31155522 0.89941798]
 [5.5        0.96999736 0.52925504]
 [6.         0.06510567 0.08527888]
 [6.5        0.94080292 0.58916964]
 [7.         0.68906079 0.36215063]
 [7.5        0.07206619 0.09023895]
 [8.         0.37070818 0.06541567]
 [8.5        0.32307269 0.54501816]
 [9.         0.15927369 0.27373841]
 [9.5        0.49462728 0.17759489]]


In [36]:
len(random)
len(nrandom)

20

In [6]:
mask = (nrandom[:,0]>=4) & (nrandom[:,0]<=7)
print(mask)

[False False False False False False False False  True  True  True  True
  True  True  True False False False False False]


In [22]:
maskd=nrandom[mask]
print(maskd)

[[4.         0.45884417 0.71759311]
 [4.5        0.54639421 0.61920454]
 [5.         0.67122826 0.21812257]
 [5.5        0.18191721 0.94504351]
 [6.         0.0362971  0.04731527]
 [6.5        0.29584749 0.1658747 ]
 [7.         0.82186282 0.70963597]]


In [16]:
np.arange(start=4, stop=7.5,step=.5)


array([4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ])

In [23]:
array=(maskd[:,0])
print(array)

[4.  4.5 5.  5.5 6.  6.5 7. ]


In [25]:
flux=(maskd[:,1])
print(flux)

[0.45884417 0.54639421 0.67122826 0.18191721 0.0362971  0.29584749
 0.82186282]
